### ISSUE TITLE
Renovate

### ISSUE THREAD

**Issue by jeff-cook** [textlint-rule/textlint-rule-alex#5]
Check out https://github.com/marketplace/renovate to keep the dependencies up to date.

**Comment by azu** [comment]
We should resolve  #4 before setup renovate.

My renovateconfig is [@azu/renovate-config](https://github.com/azu/renovate-config).

**Comment by jeff-cook** [comment]
Alex is going to wait for their next major release to update the module in #4. They do this yearly. So no need to wait for #4 to add Renovate.
